apiVersion: eks.aws.crossplane.jonashackt.io/v1alpha1
kind: EKSCluster
metadata:
  namespace: default
  name: deploy-target-eks
spec:
  id: deploy-target-eks
  parameters:
    subnetIds:
      - subnet-04b3c3cb1f127873c
      - subnet-0b9ce14c15db2d384
      - subnet-0cfbc695abf784429     
    securityGroupClusterIds:
      - sg-04f65768e7a9e5aad
    region: eu-central-1
    nodes:
      count: 3
  # Crossplane creates the secret object in the same namespace as the Claim
  # see https://docs.crossplane.io/latest/concepts/claims/#claim-connection-secrets
  writeConnectionSecretToRef:
    name: eks-cluster-kubeconfig