name: publish

# Only trigger, when the resouces-rendering-test workflow succeeded
on:
  workflow_run:
    workflows: ["resouces-rendering-test"]
    types:
      - completed

env:
  GHCR_PAT: ${{ secrets.GHCR_PAT }}
  CONFIGURATION_VERSION: "v0.0.2"

jobs:
  build-configuration-and-publish-to-ghcr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Install Crossplane CLI
        run: |
          # This currently gives an error: Failed to download Crossplane CLI. Please make sure version current exists on channel stable.
          # curl -sL "https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh" |sh
          # So using manual download, see https://docs.crossplane.io/latest/cli/
          curl -sfLo crossplane "https://releases.crossplane.io/stable/current/bin/linux_amd64/crank"
          sudo mv crossplane /usr/local/bin

      - name: Build Crossplane Configuration package & publish it to GitHub Container Registry
        run: |
          echo "### Build Configuration .xpkg file"
          crossplane xpkg build --package-root=. --ignore=".github/workflows/*,examples/*" --verbose

          echo "### Publish as OCI image to GHCR"
          crossplane xpkg push "ghcr.io/jonashackt/crossplane-eks-cluster:$CONFIGURATION_VERSION" --domain=https://ghcr.io --verbose