name: publish

on: [push]

env:
  PACKAGE_VERSION: v0.0.1

jobs:
  build-configuration-and-publish-to-ghcr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Crossplane CLI
        run: |
          curl -sL "https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh" |sh
          sudo mv crossplane /usr/local/bin

      - name: Build Crossplane Configuration package & publish it to GitHub Container Registry
        run: |
          echo "### Build Configuration .xpkg file"
          crossplane xpkg build --package-root=. --ignore=".github/workflows/*,examples/*" --verbose

          echo "### Publish as OCI image to GHCR"
          crossplane xpkg push ghcr.io/jonashackt/crossplane-eks-cluster:"$KIND_NODE_VERSION" --domain=https://ghcr.io --verbose